"""empty message

Revision ID: 4dfafb032ddb
Revises: 
Create Date: 2022-04-22 16:02:23.785159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dfafb032ddb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('shortname', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conferences')),
    sa.UniqueConstraint('name', name=op.f('uq_conferences_name')),
    sa.UniqueConstraint('shortname', name=op.f('uq_conferences_shortname'))
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_count', sa.Integer(), nullable=True),
    sa.Column('max_rounds', sa.Integer(), nullable=True),
    sa.Column('current_round', sa.Integer(), nullable=True),
    sa.Column('isopen', sa.Integer(), nullable=True),
    sa.Column('site_password', sa.String(length=64), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('invite_password', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settings'))
    )
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('k', sa.String(length=64), nullable=False),
    sa.Column('v', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_status')),
    sa.UniqueConstraint('k', name=op.f('uq_status_k'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.Column('pos', sa.Integer(), nullable=False),
    sa.Column('admin', sa.Integer(), nullable=False),
    sa.Column('registered', sa.Integer(), nullable=False),
    sa.Column('active', sa.Integer(), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('display_name', name=op.f('uq_users_display_name')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('divisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('shortname', sa.String(length=16), nullable=False),
    sa.Column('conference_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['conference_id'], ['conferences.id'], name=op.f('fk_divisions_conference_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_divisions')),
    sa.UniqueConstraint('name', name=op.f('uq_divisions_name')),
    sa.UniqueConstraint('shortname', name=op.f('uq_divisions_shortname'))
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('shortname', sa.String(length=16), nullable=False),
    sa.Column('abbrev', sa.String(length=3), nullable=False),
    sa.Column('division_id', sa.Integer(), nullable=False),
    sa.Column('in_playoffs', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], name=op.f('fk_teams_division_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams')),
    sa.UniqueConstraint('abbrev', name=op.f('uq_teams_abbrev')),
    sa.UniqueConstraint('name', name=op.f('uq_teams_name')),
    sa.UniqueConstraint('shortname', name=op.f('uq_teams_shortname'))
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=64), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(length=16), nullable=False),
    sa.Column('season', sa.String(length=16), nullable=True),
    sa.Column('games', sa.Integer(), nullable=True),
    sa.Column('goals', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_players_team_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_players'))
    )
    op.create_table('logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_logs_player_id')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_logs_user_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_logs'))
    )
    op.create_table('picks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('elapsed_secs', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_picks_player_id')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_picks_user_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_picks'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('picks')
    op.drop_table('logs')
    op.drop_table('players')
    op.drop_table('teams')
    op.drop_table('divisions')
    op.drop_table('users')
    op.drop_table('status')
    op.drop_table('settings')
    op.drop_table('conferences')
    # ### end Alembic commands ###
